name: Deploy Node.js App

on:
  push:
    branches: [ main, preprod, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Execute remote script via SSH
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no  ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<EOF 
            echo "etape1" \> toto.text
            set -ex
            BRANCH="${{ github.ref_name }}"
            GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"

            if [[ "$BRANCH" == "main" ]]; then
              path="/srv/customer/site/masqip.org"
            else
              path="/srv/customer/site/${BRANCH}.masqip.org"
            fi

            cd "$path"

            echo "--- FETCH START ---"
            git -c credential.helper="" \
                -c http.extraHeader="Authorization: Bearer $GITHUB_TOKEN" \
                -c http.version=HTTP/1.1 \
                fetch https://WireSwarm@github.com/WireSwarm/MasqIP.git $BRANCH
            echo "--- FETCH DONE ---"

            git checkout "$BRANCH"
            git reset --hard FETCH_HEAD
            git clean -fd

            npm install --production
            npm run build
          EOF
