name: Deploy Node.js App

on:
  push:
    branches: [ main, preprod, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sec
    permissions:
      contents: read

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Execute remote script via SSH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
          REMOTE_SCRIPT: |
            #!/bin/bash
            echo "je suis un script"
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
          ssh -tt -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            touch tifes.txt
   
            chmod +x script.sh
            ./script.sh
            cat \<\< 'EOL' > script.sh
              echo "ustre"
            EOL
            touch frite.txt
            EOF