name: Deploy Node.js App

on:
  push:
    branches: [ main, preprod, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sec
    permissions:
      contents: read

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Write script to file
        
        run: |
          cat > script.sh << 'EOF'
          #!/bin/bash
          echo "je suis un scripttt"
          touch script.executed
          sleep 3
          echo " après le sleep"
          

          EOF
      - name : Send with scp the script
        continue-on-error: true
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
          scp -o StrictHostKeyChecking=no script.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/script.sh

      - name: Execute the script on the server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_stop: false   # équivalent au comportement de -tt pour ne pas couper le script
          request_pty: true
          envs: GITHUB_TOKEN,BRANCH
          command_timeout: 200m
          script: |
            stdbuf -oL -eL bash ./script.sh
