name: Deploy Node.js App

on:
  push:
    branches: [ main, preprod, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sec
    permissions:
      contents: read

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Write script to file
        
        run: |
          cat > script.sh << 'EOF'
          (

          set -ex

          touch sujiton6.text

          if [[ "${{ github.ref_name }}" == "main" ]]; then
            path="/srv/customer/site/masqip.org"
          else
            path="/srv/customer/site/${{ github.ref_name }}.masqip.org"
          fi

          cd "$path"
          touch sui2.text

          echo "--- FETCH START ---"
          git fetch https://WireSwarm@github.com/WireSwarm/MasqIP.git ${{ github.ref_name }}
          echo "--- FETCH DONE ---"

          touch sui3.text
          git checkout "${{ github.ref_name }}"
          git reset --hard FETCH_HEAD
          git clean -fd
          touch sui4.text

          npm install --production
          npm run build






          )> sortie.log 2>&1 &
          disown

          EOF
          chmod +x script.sh
      - name : Send with scp the script
        continue-on-error: true
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
          scp -o StrictHostKeyChecking=no script.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/script.sh

      - name: Execute the script on the server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
        continue-on-error: true
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh \
            -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          chmod +x script.sh
          ./script.sh
          sleep 5
          EOF