name: Deploy Node.js App

on:
  push:
    branches:
      - main
      - preprod
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sec

    steps:
      - name: DÃ©ploiement sur le VPS (via SSH)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "HOME in script: $HOME"
            echo "whoami: $(whoami)"

            echo "--- DEBUG CREDENTIALS ---"
            echo "HOME = $HOME"
            ls -la $HOME

            branch="${{ github.ref_name }}"
            if [[ "$branch" == "main" ]]; then
              path="/srv/customer/site/masqip.org"
            else
              path="/srv/customer/site/${branch}.masqip.org"
            fi
            
            echo "--- REMOTE ---"
            git remote -v

            echo "--- TRY FETCH WITH TRACE ---"
            GIT_TRACE=1 GIT_CURL_VERBOSE=1 git fetch origin main
            echo "We expect path: $path"
            echo "Listing parent directory:"
            ls -la /srv/customer/site || echo "/srv/customer/site NOT FOUND"

            ls -la "$path" || echo "$path DOES NOT EXIST"
            echo "Updating $path for branch $branch"
            cd $path
            echo "fetch"
            git fetch origin $branch
            echo "checkout"
            git checkout $branch
            echo "reset"
            git reset --hard origin/$branch
            echo "clean"
            git clean -fd
            echo "build"
            npm run build
            