name: Deploy Node.js App

on:
  push:
    branches: [ main, preprod, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sec
    permissions:
      contents: read

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Execute remote script via SSH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
          ssh -tt -o StrictHostKeyChecking=no  ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cat script.sh \<\<'FOE' \> script.sh
            #!/bin/bash
            touch suis.text
            set -ex
            touch sui1.text
            if [[ "$BRANCH" == "main" ]]; then
              path="/srv/customer/site/masqip.org"
            else
              path="/srv/customer/site/${BRANCH}.masqip.org"
            fi
            cd "$path"
            touch sui2.text
            echo "--- FETCH START ---"
            git -c credential.helper="" \
                -c http.extraHeader="Authorization: Bearer $GITHUB_TOKEN" \
                -c http.version=HTTP/1.1 \
                fetch https://WireSwarm@github.com/WireSwarm/MasqIP.git $BRANCH
            echo "--- FETCH DONE ---"
            touch sui3.text
            git checkout "$BRANCH"
            git reset --hard FETCH_HEAD
            git clean -fd
            touch sui4.text
            npm install --production
            npm run build
            FOE
            chmod +x script.sh
            ./script.sh >> sortie.txt 2>&1
          EOF
