name: Deploy Node.js App

on:
  push:
    branches:
      - main
      - preprod
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sec
    permissions:
      contents: read

    steps:
      - name: Déploiement sur le VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: GITHUB_TOKEN
          request_pty: true     # ← IMPORTANT
          
          script: |
            trap '' HUP

            branch="${{ github.ref_name }}"
            if [[ "$branch" == "main" ]]; then
              path="/srv/customer/site/masqip.org"
            else
              path="/srv/customer/site/${branch}.masqip.org"
            fi

            cd $path

            echo "Fetch secured"
            git -c credential.helper= \
                -c http.extraHeader="Authorization: Bearer ${GITHUB_TOKEN}" \
                fetch https://github.com/WireSwarm/MasqIP.git $branch

            git checkout $branch
            git reset --hard FETCH_HEAD
            git clean -fd

            npm install --production
            npm run build
