name: Deploy Node.js App

on:
  push:
    branches:
      - main
      - preprod
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sec
    permissions:
      contents: read

    steps:
      - name: SSH via stable client
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASSWORD }}
          envs: GITHUB_TOKEN,BRANCH  
          command: |
            set -ex

            BRANCH="${{ github.ref_name }}"
            GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"

            if [[ "$BRANCH" == "main" ]]; then
              path="/srv/customer/site/masqip.org"
            else
              path="/srv/customer/site/${BRANCH}.masqip.org"
            fi

            cd "$path"
            echo "Branche = $BRANCH"

            GIT_TRACE=1 GIT_CURL_VERBOSE=1 \
            git -c credential.helper="" \
                -c http.extraHeader="Authorization: Bearer $GITHUB_TOKEN" \
                -c http.version=HTTP/1.1 \
                fetch --quiet https://WireSwarm@github.com/WireSwarm/MasqIP.git $BRANCH

            git checkout "$BRANCH"
            git reset --hard FETCH_HEAD
            git clean -fd

            npm install --production
            npm run build