name: Deploy Node.js App

on:
  push:
    branches:
      - main
      - preprod
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: DÃ©ploiement sur le VPS (via SSH)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            branch=${GITHUB_REF_NAME}
            if [[ "$branch" == "main" ]]; then
              path="/home/site/masqip.org"
            else
              path="/home/site/${branch}.masqip.org"
            fi

            echo "Updating $path for branch $branch"
            cd $path
            git fetch origin $branch
            git checkout $branch
            git reset --hard origin/$branch
            git clean -fd
            npm run build
            