name: Deploy Node.js App

on:
  push:
    branches:
      - main
      - preprod
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sec
    permissions:
      contents: read

    steps:
      - name: SSH via stable client
        uses: fifsky/ssh-action
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASSWORD }}
          command:  |

            branch="${{ github.ref_name }}"
            if [[ "$branch" == "main" ]]; then
              path="/srv/customer/site/masqip.org"
            else
              path="/srv/customer/site/${branch}.masqip.org"
            fi

            cd $path
            echo "La branche est $branch"
            echo "Fetch secured"
            GIT_TRACE=1 GIT_CURL_VERBOSE=1 \
            git -c credential.helper="" \
                -c http.extraHeader="Authorization: Bearer ${GITHUB_TOKEN}" \
                -c http.version=HTTP/1.1 \
                fetch --quiet https://WireSwarm@github.com/WireSwarm/MasqIP.git $branch
            echo "After fetch"
            git checkout $branch
            git reset --hard FETCH_HEAD
            git clean -fd

            npm install --production
            npm run build
